name: Daily Expo Scrape

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily scraper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIREBASE_SA: ${{ secrets.FIREBASE_SA }}
        run: |
          echo "$FIREBASE_SA" > firebase-admin.json
          python scripts/run_daily.py
